### ISSUE TITLE
faire les politiques de confidentialités, conditions de ventes, etc

### ISSUE THREAD

**Issue by philippe-nougaillon** [philippe-nougaillon/PrestoFacto#55]

**Comment by P-edacquet** [comment]
https://www.entreprises.cci-paris-idf.fr/web/reglementation/contrats-modeles/commerciaux/conditions-generales-de-vente-entre-professionnels

**Comment by P-edacquet** [comment]
https://www.emedia-informatique.com/conditions-generales-de-vente-et-prestations-de-services/
